<Project>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestoreUseStaticGraphEvaluation>true</RestoreUseStaticGraphEvaluation>
    <UseSharedCompilation>true</UseSharedCompilation>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CI)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
